version: '3'

services:
  postgresdb:
    image: postgres:15-alpine
    restart: always
    container_name: posgres_mymemories
    volumes:
      - ./postgres-docker:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: my-memories
      POSTGRES_PASSWORD: mymemories
      POSTGRES_DB: my_memories_db
    ports:
      - '5434:5432'
    networks:
      - backend
  jenkins:
    image: gabrieldasilvadev/jenkins-mymemories
    container_name: jenkins_mymemories
    restart: unless-stopped
    build: .
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home

volumes:
  jenkins_home:

networks:
  backend:
    driver: bridge