#!/usr/bin/env groovy
pipeline {
    agent any
    stages {
        stage('Lint') {
            steps {
                echo 'executing lint format'
                withGradle() {
                    sh './gradlew ktlintFormat'
                }
            }
        }
        stage('Test') {
            steps {
                withGradle() {
                    sh './gradlew test'
                }
            }
        }
        stage('Build') {
            steps {
                withGradle() {
                    sh './gradlew clean build'
                }
            }
        }
    }
}