#!/usr/bin/env groovy
pipeline {
    agent any
    stages {
        stage('Permission gradle') {
            steps {
                echo 'Given all permissions for gradle'
                withGradle() {
                    sh 'chmod 777 ./gradlew'
                }
            }
        }
        stage('Check gradle version') {
            steps {
                echo 'Check gradle version'
                withGradle() {
                    sh './gradlew --version'
                }
            }
        }
        stage('Lint') {
            steps {
                echo 'executing lint format'
                withGradle() {
                    sh './gradlew ktlintFormat'
                }
            }
        }
        stage('Unit tests') {
            steps {
                echo 'Executing unit testing'
                withGradle() {
                    sh './gradlew test'
                }
            }
        }
        stage('Build') {
            steps {
                withGradle() {
                    sh './gradlew build -x test --stacktrace'
                }
            }
        }
    }
}